'use client'

import QRCode from 'qrcode'
import { useCallback, useEffect, useRef, useState } from 'react'

import styles from '../ChatInterface.module.css'
import {
  WEIXIN_CLAWBOT_USER_API_PATH,
  WEIXIN_CLAWBOT_USER_QRCODE_API_PATH,
  WEIXIN_CLAWBOT_USER_QRCODE_STATUS_API_PATH,
  WEIXIN_CLAWBOT_USERS_API_PATH,
} from './constants'
import type {
  WeixinClawBotBoundUser,
  WeixinClawBotBoundUserDeleteResponse,
  WeixinClawBotBoundUserListResponse,
  WeixinClawBotQrcodeResponse,
  WeixinClawBotQrcodeStatusResponse,
} from './types'
import { fetchJson, formatDateTime, getApiUrl } from './utils'

interface ChannelManagementViewProps {
  userId: string
}

function getResponseQrcodeUrl(
  response?: WeixinClawBotQrcodeResponse | WeixinClawBotQrcodeStatusResponse | null
): string {
  const qrcodeUrl = response?.qrcode_url
  if (typeof qrcodeUrl === 'string' && qrcodeUrl.trim()) return qrcodeUrl

  const qrcode = response?.qrcode
  if (
    typeof qrcode === 'string' &&
    (qrcode.startsWith('http://') || qrcode.startsWith('https://'))
  ) {
    return qrcode
  }

  return ''
}

function getQrcodePayload(
  qrcode: WeixinClawBotQrcodeResponse | null,
  status: WeixinClawBotQrcodeStatusResponse | null
): string {
  return (
    (typeof qrcode?.qrcode === 'string' && qrcode.qrcode) ||
    (typeof status?.qrcode === 'string' && status.qrcode) ||
    getResponseQrcodeUrl(qrcode) ||
    getResponseQrcodeUrl(status)
  )
}

function getBaseUrl(status?: WeixinClawBotQrcodeStatusResponse | null): string {
  return status?.baseurl || status?.base_url || '未获取'
}

function formatRawStatus(status?: WeixinClawBotQrcodeStatusResponse | null): string {
  if (!status) return '暂无状态'
  return JSON.stringify(
    {
      status: status.status ?? null,
      has_bot_token: Boolean(status.bot_token),
      baseurl: status.baseurl ?? status.base_url ?? null,
    },
    null,
    2
  )
}

export function ChannelManagementView({ userId }: ChannelManagementViewProps) {
  const autoGeneratedUserIdRef = useRef('')
  const [targetUserId, setTargetUserId] = useState(userId)
  const [boundUsers, setBoundUsers] = useState<WeixinClawBotBoundUser[]>([])
  const [qrcode, setQrcode] = useState<WeixinClawBotQrcodeResponse | null>(null)
  const [status, setStatus] =
    useState<WeixinClawBotQrcodeStatusResponse | null>(null)
  const [qrcodeDataUrl, setQrcodeDataUrl] = useState('')
  const [loadingUsers, setLoadingUsers] = useState(false)
  const [loadingQrcode, setLoadingQrcode] = useState(false)
  const [checkingStatus, setCheckingStatus] = useState(false)
  const [deletingUserId, setDeletingUserId] = useState('')
  const [autoPolling, setAutoPolling] = useState(false)
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')

  const qrcodeUrl = getResponseQrcodeUrl(qrcode) || getResponseQrcodeUrl(status)
  const qrcodePayload = getQrcodePayload(qrcode, status)
  const connected = Boolean(status?.bot_token)
  const connectionLabel = connected
    ? '已连接'
    : autoPolling
      ? '等待扫码'
      : qrcodePayload
        ? '二维码已生成'
        : '未连接'

  const loadBoundUsers = useCallback(async () => {
    setLoadingUsers(true)
    setError('')
    try {
      const response = await fetchJson<WeixinClawBotBoundUserListResponse>(
        getApiUrl(WEIXIN_CLAWBOT_USERS_API_PATH)
      )
      setBoundUsers(response.items)
    } catch (nextError) {
      setError(nextError instanceof Error ? nextError.message : String(nextError))
    } finally {
      setLoadingUsers(false)
    }
  }, [])

  const checkStatus = useCallback(
    async (userIdToCheck = targetUserId) => {
      const normalizedUserId = userIdToCheck.trim()
      if (!normalizedUserId) {
        setError('请先输入要绑定的 user_id。')
        return
      }

      setCheckingStatus(true)
      setError('')
      try {
        const nextStatus = await fetchJson<WeixinClawBotQrcodeStatusResponse>(
          getApiUrl(WEIXIN_CLAWBOT_USER_QRCODE_STATUS_API_PATH(normalizedUserId))
        )
        setStatus(nextStatus)
        const nextQrcodeUrl = getResponseQrcodeUrl(nextStatus)
        if (nextQrcodeUrl) {
          setQrcode((current) =>
            getResponseQrcodeUrl(current) ? current : { qrcode_url: nextQrcodeUrl }
          )
        }

        if (nextStatus.bot_token) {
          setAutoPolling(false)
          setNotice(`用户 ${normalizedUserId} 已扫码确认，后端已启动微信 ClawBot 轮询。`)
          await loadBoundUsers()
        } else if (nextStatus.status) {
          setNotice(`用户 ${normalizedUserId} 当前扫码状态：${nextStatus.status}`)
        } else {
          setNotice(`用户 ${normalizedUserId} 还没有获取到扫码确认状态。`)
        }
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : String(nextError))
      } finally {
        setCheckingStatus(false)
      }
    },
    [loadBoundUsers, targetUserId]
  )

  const generateQrcode = useCallback(
    async (userIdToBind = targetUserId) => {
      const normalizedUserId = userIdToBind.trim()
      if (!normalizedUserId) {
        setError('请先输入要绑定的 user_id。')
        return
      }

      setTargetUserId(normalizedUserId)
      setLoadingQrcode(true)
      setError('')
      setNotice('')
      setStatus(null)
      try {
        const nextQrcode = await fetchJson<WeixinClawBotQrcodeResponse>(
          getApiUrl(WEIXIN_CLAWBOT_USER_QRCODE_API_PATH(normalizedUserId)),
          { method: 'POST' }
        )
        setQrcode(nextQrcode)
        setAutoPolling(true)
        setNotice(`用户 ${normalizedUserId} 的二维码已生成，请用该用户自己的微信扫码。`)
        await loadBoundUsers()
      } catch (nextError) {
        setAutoPolling(false)
        setError(nextError instanceof Error ? nextError.message : String(nextError))
      } finally {
        setLoadingQrcode(false)
      }
    },
    [loadBoundUsers, targetUserId]
  )

  const deleteBoundUser = useCallback(
    async (userIdToDelete: string) => {
      if (
        typeof window !== 'undefined' &&
        !window.confirm(`确认删除用户 ${userIdToDelete} 的微信 ClawBot 绑定吗？`)
      ) {
        return
      }

      setDeletingUserId(userIdToDelete)
      setError('')
      try {
        await fetchJson<WeixinClawBotBoundUserDeleteResponse>(
          getApiUrl(WEIXIN_CLAWBOT_USER_API_PATH(userIdToDelete)),
          { method: 'DELETE' }
        )
        setNotice(`用户 ${userIdToDelete} 的微信绑定已删除。`)
        if (targetUserId === userIdToDelete) {
          setQrcode(null)
          setStatus(null)
          setAutoPolling(false)
        }
        await loadBoundUsers()
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : String(nextError))
      } finally {
        setDeletingUserId('')
      }
    },
    [loadBoundUsers, targetUserId]
  )

  useEffect(() => {
    setTargetUserId(userId)
  }, [userId])

  useEffect(() => {
    void loadBoundUsers()
  }, [loadBoundUsers])

  useEffect(() => {
    const normalizedUserId = userId.trim()
    if (!normalizedUserId || autoGeneratedUserIdRef.current === normalizedUserId) {
      return
    }

    autoGeneratedUserIdRef.current = normalizedUserId
    void generateQrcode(normalizedUserId)
  }, [generateQrcode, userId])

  useEffect(() => {
    if (!qrcodePayload) {
      setQrcodeDataUrl('')
      return
    }

    let cancelled = false
    void QRCode.toDataURL(qrcodePayload, {
      errorCorrectionLevel: 'M',
      margin: 2,
      width: 240,
    })
      .then((nextDataUrl) => {
        if (!cancelled) setQrcodeDataUrl(nextDataUrl)
      })
      .catch((nextError: unknown) => {
        if (!cancelled) {
          setQrcodeDataUrl('')
          setError(nextError instanceof Error ? nextError.message : String(nextError))
        }
      })

    return () => {
      cancelled = true
    }
  }, [qrcodePayload])

  useEffect(() => {
    if (!autoPolling || connected) return

    const timer = window.setInterval(() => {
      void checkStatus()
    }, 2000)

    return () => window.clearInterval(timer)
  }, [autoPolling, checkStatus, connected])

  return (
    <div className={styles.managementWorkspace}>
      <section className={styles.managementHero}>
        <div className={styles.managementHeroCopy}>
          <span className={styles.managementHeroEyebrow}>Channel Management</span>
          <h2>渠道管理</h2>
          <p>
            这里集中管理外部渠道和 Agent 的绑定关系。当前已接入微信 ClawBot，
            每个 user_id 都需要独立扫码接入自己的微信账号。
          </p>
        </div>
        <div className={styles.managementHeroActions}>
          <button
            className={styles.managementMinorButton}
            disabled={loadingUsers}
            onClick={() => void loadBoundUsers()}
          >
            {loadingUsers ? '刷新中...' : '刷新绑定列表'}
          </button>
        </div>
      </section>

      <div className={styles.managementNoticeRow}>
        {notice ? <div className={styles.managementNotice}>{notice}</div> : null}
        {error ? <div className={styles.managementError}>{error}</div> : null}
      </div>

      <div className={styles.managementSummaryGrid}>
        <div className={styles.managementSummaryCard}>
          <span className={styles.managementSummaryLabel}>已绑定用户</span>
          <strong className={styles.managementSummaryValue}>{boundUsers.length}</strong>
          <span className={styles.managementMeta}>微信 ClawBot 独立扫码用户数</span>
        </div>
        <div className={styles.managementSummaryCard}>
          <span className={styles.managementSummaryLabel}>当前操作用户</span>
          <strong className={styles.managementSummaryValue}>
            {targetUserId || '未设置'}
          </strong>
          <span className={styles.managementMeta}>添加或刷新二维码时使用</span>
        </div>
        <div className={styles.managementSummaryCard}>
          <span className={styles.managementSummaryLabel}>扫码状态</span>
          <strong className={styles.managementSummaryValue}>{connectionLabel}</strong>
          <span className={styles.managementMeta}>
            {autoPolling ? '正在每 2 秒自动检查一次' : '可手动检查最新状态'}
          </span>
        </div>
        <div className={styles.managementSummaryCard}>
          <span className={styles.managementSummaryLabel}>ClawBot 节点</span>
          <strong className={styles.managementSummaryValue}>{getBaseUrl(status)}</strong>
          <span className={styles.managementMeta}>扫码确认后由 ClawBot 返回</span>
        </div>
      </div>

      <div className={styles.managementPageGrid}>
        <section className={styles.managementCard}>
          <div className={styles.managementHeader}>
            <h3>微信 ClawBot 绑定</h3>
            <span className={styles.managementMeta}>添加用户并扫码</span>
          </div>

          <div className={styles.managementToolbar}>
            <input
              className={styles.managementInput}
              value={targetUserId}
              onChange={(event) => setTargetUserId(event.target.value)}
              placeholder="输入要绑定的 user_id"
            />
            <button
              className={styles.managementMinorButton}
              disabled={!userId}
              onClick={() => setTargetUserId(userId)}
            >
              使用当前用户
            </button>
            <button
              className={styles.managementButton}
              disabled={loadingQrcode || !targetUserId.trim()}
              onClick={() => void generateQrcode()}
            >
              {loadingQrcode ? '生成中...' : '添加/刷新二维码'}
            </button>
          </div>

          <div className={styles.managementMetaPanel}>
            <span>绑定规则: 每个 user_id 都必须扫码接入自己的微信账号</span>
            <span>消息归属: 后端按 user_id 隔离微信会话和 Agent 会话</span>
            <span>轮询策略: 扫码确认后后端自动启动该用户的 ClawBot poll</span>
          </div>

          <div className={styles.channelQrPanel}>
            {qrcodeDataUrl ? (
              <img
                className={styles.channelQrImage}
                src={qrcodeDataUrl}
                alt={`${targetUserId} 微信 ClawBot 登录二维码`}
              />
            ) : (
              <div className={styles.channelQrPlaceholder}>等待生成二维码</div>
            )}

            <div className={styles.channelQrDetails}>
              <strong>二维码链接</strong>
              {qrcodeUrl ? (
                <a
                  className={`${styles.managementLink} ${styles.channelQrLink}`}
                  href={qrcodeUrl}
                  target="_blank"
                  rel="noreferrer"
                >
                  {qrcodeUrl}
                </a>
              ) : (
                <span className={styles.managementMeta}>生成后会显示可点击 URL</span>
              )}
              <div className={styles.managementActionRow}>
                <button
                  className={styles.managementMinorButton}
                  disabled={checkingStatus || !targetUserId.trim()}
                  onClick={() => void checkStatus()}
                >
                  {checkingStatus ? '检查中...' : '检查扫码状态'}
                </button>
              </div>
            </div>
          </div>

          <textarea
            className={styles.managementTextarea}
            value={formatRawStatus(status)}
            readOnly
            rows={7}
            spellCheck={false}
          />
        </section>

        <section className={styles.managementCard}>
          <div className={styles.managementHeader}>
            <h3>已绑定用户</h3>
            <span className={styles.managementMeta}>
              {loadingUsers ? '加载中...' : `${boundUsers.length} 个用户`}
            </span>
          </div>

          <div className={styles.managementList}>
            {boundUsers.length === 0 ? (
              <div className={styles.managementEmpty}>
                当前还没有微信 ClawBot 绑定用户。输入 user_id 后生成二维码并扫码即可添加。
              </div>
            ) : (
              boundUsers.map((boundUser) => (
                <div
                  key={boundUser.state_key}
                  className={styles.managementListItemStatic}
                >
                  <div className={styles.managementListHeader}>
                    <strong>{boundUser.user_id}</strong>
                    <span>{boundUser.connected ? '已连接' : '待扫码'}</span>
                  </div>
                  <p className={styles.managementDescription}>
                    {boundUser.base_url || '暂未获取 ClawBot 节点'}
                  </p>
                  <div className={styles.managementListMeta}>
                    <span>Token: {boundUser.bot_token || '未获取'}</span>
                    <span>状态: {boundUser.status}</span>
                    <span>更新: {formatDateTime(boundUser.updated_at)}</span>
                  </div>
                  <div className={styles.managementActionRow}>
                    <button
                      className={styles.managementMinorButton}
                      disabled={loadingQrcode}
                      onClick={() => void generateQrcode(boundUser.user_id)}
                    >
                      重新扫码
                    </button>
                    <button
                      className={styles.managementDangerMinorButton}
                      disabled={deletingUserId === boundUser.user_id}
                      onClick={() => void deleteBoundUser(boundUser.user_id)}
                    >
                      {deletingUserId === boundUser.user_id ? '删除中...' : '删除绑定'}
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </section>
      </div>
    </div>
  )
}
